#!/bin/sh
#
# eawpatches-package - build a Debian package of eawpatches
#
# Copyright © 2014 Frédéric Brière <fbriere@fbriere.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

# Bunch of URLs that will be tried out (in random order) by default
# (Blank lines and comment lines are allowed)
DEFAULT_URLS="
	ftp://ftp.gr.freebsd.org/pub/vendors/idgames/sounds/eawpats.zip
	ftp://ftp.cubic.org/pub/player/patches/eawpats.zip
	ftp://ftp.fu-berlin.de/pc/games/idgames/sounds/eawpats.zip
	ftp://psg.mtu.edu/idgames/sounds/eawpats.zip
	ftp://78.46.141.148/mirrors/ftp.cubic.org/player/patches/eawpats.zip
	ftp://mancubus.net/pub/idgames/sounds/eawpats.zip

	http://ftp.mancubus.net/pub/idgames/sounds/eawpats.zip
	http://youfailit.net/pub/idgames/sounds/eawpats.zip

	ftp://ftp.netbsd.org/pub/pkgsrc/distfiles/eawpats12_full.tar.gz
	ftp://ftp.gtlib.gatech.edu/pub/gentoo/distfiles/eawpats12_full.tar.gz
"


usage() {
	cat <<EOF
Usage: $0 [ <options> ... ] [ <url> | <filename> ]

Options:
  --fullname <name>   Full name in Maintainer field  [$OPT_FULLNAME]
  --email <email>     Email address in Maintainer field  [$OPT_EMAIL]
  --no-ftp            Do not try to fetch ftp: URLs
  --force             Override safety checks
  --list-urls         Display the list of URLs used by default
  --help              Show this help message
EOF
}

# Set default args early on -- they may be displayed in usage()
set_default_args() {
	# (This is mostly copied from googleearth-package)
	local SYS_MAILNAME="$(cat /etc/mailname 2>/dev/null)"
	OPT_FULLNAME="${DEBFULLNAME:-${NAME:-$(getent passwd "$(whoami)" | cut -d ':' -f 5 | cut -d ',' -f 1)}}"
	OPT_EMAIL="${DEBEMAIL:-${EMAIL:-$(whoami)@${SYS_MAILNAME:-$(hostname --fqdn)}}}"
}

# Process command-line arguments, setting $OPT_* variables
parse_args() {
	local ARG

	while [ $# -gt 0 ]; do
		ARG="$1"
		shift

		case "$ARG" in
			--fullname)
				OPT_FULLNAME="$1"
				shift
				;;
			--email)
				OPT_EMAIL="$1"
				shift
				;;
			--force)
				OPT_FORCE=true
				;;
			--no-ftp)
				OPT_NO_FTP=true
				;;
			--list-urls)
				default_urls
				exit 0
				;;
			--help)
				usage
				exit 0
				;;
			--*)
				echo "$0: unknown option $ARG" >&2
				echo "Try '$0 --help' for more information." >&2
				exit 1
				;;
			*)
				# Only allow one source
				if [ "$OPT_SOURCE" ]; then
					usage
					exit 1
				else
					OPT_SOURCE="$ARG"
				fi
				;;
		esac
	done
}

# Inspired by googleearth-package
verify_sanity() {
	if [ $(id --user) -eq 0 ]; then
		echo 'Refusing to run as root; use --force to override.' >&2
		return 1
	fi

	if [ -u . -o -g . ]; then
		echo 'Refusing to build in a setuid/setgid directory; use --force to override.' >&2
		return 1
	fi
}

# Set up download() - download <url> <output-file>
if which wget > /dev/null; then
	download() {
		wget "$1" -O "$2" || return 1
	}
elif which curl > /dev/null; then
	download() {
		curl "$1" -o "$2" || return 1
	}
else
	download() {
		echo 'Either wget or curl is required to download the eawpatches archive.' >&2
		echo '(Or you can download it yourself and point to it.)' >&2
		exit 1
	}
fi

# Check the MD5 of a file against known values
check_md5sum() {
	case "$(md5sum "$1" | cut -d ' ' -f 1)" in
		323c540c5a7923f7cf5a220fc1b7f4a4) true ;;  # zip
		8ebcf0583f3077346ebace93c8ea166f) true ;;  # tar
		*) false ;;
	esac
}

# Extract the contents of a (possible) archive
extract() {
	local FILE="$1" DEST="$2"
	shift 2

	# --test-label does not appear to work  :(
	if tar -t -f "$FILE" >/dev/null 2>&1; then
		tar x -f "$FILE" -C "$DEST"
	elif zipinfo -h "$FILE" >/dev/null 2>&1; then
		unzip -q "$FILE" -d "$DEST"
	else
		return 1
	fi
}

# Figure out the root directory of an extracted archive
root_dir() {
	local DIR="$1"
	shift

	if ls "$DIR"/*.pat >/dev/null 2>&1; then
		echo "$DIR"
		return 0
	elif ls "$DIR"/*/*.pat >/dev/null 2>&1; then
		# Make sure there is only one top subdirectory
		if [ $(ls -d "$DIR"/* | wc -l) -eq 1 ]; then
			echo "$DIR"/*
			return 0
		fi
	fi

	return 1
}

# Directory where we will find our misc. files
misc_dir() {
	local SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

	if [ "$SCRIPT_DIR" = "/usr/bin" ]; then
		# We are running from an installed Debian package
		echo "/usr/share/eawpatches-package"
	elif [ -d "$SCRIPT_DIR/debian" -a -d "$SCRIPT_DIR/eawpatches" ]; then
		# We appear to be running from the unpacked source
		echo "$SCRIPT_DIR/eawpatches"
	else
		echo "$0: Unable to find misc. files directory" >&2
		return 1
	fi
}

# Build the filesystem tree for our binary package from an unpacked archive.
build_deb_tree() {
	local SRC="$1" DEST="$2"
	shift 2

	# Some additional files that we'll need
	local SHARE="$(misc_dir)"
	# We'll refer to this directory a lot
	local DOC="$DEST/usr/share/doc/eawpatches"

	# Copy all *.pat files (preserving directories)
	mkdir -p "$DEST/usr/share/midi/eawpatches"
	find "$SRC" -name '*.pat' -printf '%P\n' \
		| tar c -C "$SRC" --files-from=- \
		| tar x -C "$DEST/usr/share/midi/eawpatches"

	# Copy all *.cfg files, along with our eawpatches.cfg
	mkdir -p "$DEST/etc/timidity/eawpatches"
	cp "$SRC"/*.cfg "$DEST/etc/timidity/eawpatches/"
	cp "$SHARE/eawpatches.cfg" "$DEST/etc/timidity/"
	# winconfig/timidity.cfg is moved to the root in the .zip version
	rm -f "$DEST/etc/timidity/eawpatches/timidity.cfg"

	# The .tar.gz version has one more line at the end of gravis.cfg, as
	# compared to the .zip version -- it looks like a duplicate to me.
	sed -i '/88 surdo/d' "$DEST/etc/timidity/eawpatches/gravis.cfg"

	# Documentation (under /usr/share/doc/eawpatches)
	mkdir -p "$DOC"
	# Copy all *.txt files, except changelog.txt and copyrigh.txt
	find "$SRC" -name '*.txt' \! -name changelog.txt \! -name copyrigh.txt -print0 \
		| xargs -0 cp --target-directory "$DOC/"
	# eawpats.txt is renamed eawpats.doc in the .zip version
	[ -e "$SRC/eawpats.doc" ] && cp "$SRC/eawpats.doc" "$DOC/eawpats.txt"
	# Copy the changelog under its proper name
	cp "$SRC/changelog.txt" "$DOC/changelog"
	gzip -9 --no-name "$DOC/changelog"
	# Same with copyright, and prepend our own header
	cp "$SHARE/copyright" "$DOC/"
	cat "$SRC/copyrigh.txt" >> "$DOC/copyright"
	if [ -e "$SHARE/../debian/changelog" ]; then
		gzip -9 -c --no-name "$SHARE/../debian/changelog" > "$DOC/changelog.Debian.gz"
	else
		# Borrow the Debian changelog from eawpatches-package
		cp /usr/share/doc/eawpatches-package/changelog.gz "$DOC/changelog.Debian.gz"
	fi
	# README.Debian
	cp "$SHARE/README.Debian" "$DOC/"
	# Finally, compress anything over 4 KiB (except copyright)
	find "$DOC" -size +4k \! -name 'copyright' \! -name '*.gz' -print0 \
		| xargs -0 gzip -9 --no-name

	# lintian override for package-contains-ancient-file
	mkdir -p "$DEST/usr/share/lintian/overrides"
	cp "$SHARE/lintian-overrides" "$DEST/usr/share/lintian/overrides/eawpatches"

	# DEBIAN directory
	mkdir -p "$DEST/DEBIAN"
	sed -e "s/\${local:Maintainer}/${OPT_FULLNAME} <${OPT_EMAIL}>/g" \
		"$SHARE/control" > "$DEST/DEBIAN/control"
	sed -i "s/\${local:Installed-Size}/$(du -k -s --apparent-size "$DEST" | cut -f1)/g" "$DEST/DEBIAN/control"
	if [ -e "$SHARE/../debian/changelog" ]; then
		# This is very hackish, but we cannot rely on
		# dpkg-parsechangelog to be available  :(
		sed -i "s/\${local:Version}/$(sed -n '1 s/.*(\(.*\)).*/\1/p' "$SHARE/../debian/changelog")/g" "$DEST/DEBIAN/control"
	fi
	# Generate conffiles
	find "$DEST/etc" -type f -printf '/etc/%P\n' | sort >> "$DEST/DEBIAN/conffiles"
	# Generate md5sums (which must be relative to $DEST)
	(cd "$DEST" && find . -type f \! -regex './\(DEBIAN\|etc\)/.*' -printf '%P\0' \
		| LC_ALL=C sort --zero-terminated \
		| xargs -0 md5sum) > "$DEST/DEBIAN/md5sums"

	# This file's timestamp elicits a warning from tar, which in turn confuses
	# apt-ftparchive (see bug #434824).
	#touch -d '1990-01-01 00:00:00' "$DEST/usr/share/midi/eawpatches/charang.pat"

	# Fix permissions
	find "$DEST" -type f -print0 | xargs -0 chmod 644
	find "$DEST" -type d -print0 | xargs -0 chmod 755
}

# Process a single (possible) archive
process_file() {
	local WORK_DIR="$1" FILENAME="$2"
	shift 2

	if ! check_md5sum "$FILENAME"; then
		echo "$FILENAME: wrong checksum -- file is probably corrupt or invalid" >&2
		if [ "$OPT_FORCE" = true ]; then
			echo "Ignoring as requested by --force" >&2
		else
			echo "Use --force to ignore this error." >&2
			return 1
		fi
	fi

	rm -rf "$WORK_DIR/src"
	mkdir -p "$WORK_DIR/src"

	if ! extract "$FILENAME" "$WORK_DIR/src"; then
		echo "$FILENAME: unknown file type" >&2
		# Try to be helpful
		if ! which unzip >/dev/null; then
			echo "(Did you install unzip?)" >&2
		fi
		return 1
	fi

	if ROOT_DIR="$(root_dir "$WORK_DIR/src")"; then
		mkdir -p "$WORK_DIR/build"
		build_deb_tree "$ROOT_DIR" "$WORK_DIR/build"
	else
		echo "Could not find appropriate contents in $FILENAME" >&2
		return 1
	fi
}

process_url() {
	local WORK_DIR="$1" URL="$2"
	shift 2

	case "$URL" in
		ftp:*)
			if [ "$OPT_NO_FTP" = true ]; then
				echo "Not downloading <$URL>: --no-ftp was specified" >&2
				return 1
			fi
			;;
		*.zip | *.ZIP)
			if [ ! "$(which unzip)" -a "$OPT_FORCE" != true ]; then
				echo "Not downloading <$URL>: unzip not available; use --force to override" >&2
				return 1
			fi
			;;
	esac

	download "$URL" "$WORK_DIR/eawpatches.bin" \
		&& process_file "$WORK_DIR" "$WORK_DIR/eawpatches.bin" \
		&& return 0

	return 1
}

process_file_or_url() {
	local WORK_DIR="$1" ARG="$2"

	case "$ARG" in
		http://* | ftp://*)
			process_url "$WORK_DIR" "$ARG"
			;;
		*)
			if [ ! -f "$ARG" ]; then
				echo "$0: $ARG: No such file" >&2
				return 1
			fi
			process_file "$WORK_DIR" "$ARG"
			;;
	esac
}

# Returns a cleaned-up and filtered $DEFAULT_URLS
default_urls() {
	echo "$DEFAULT_URLS" |\
		sed 's/^\s\+//' |\
		egrep -v '^(#|$)' |\
		if [ ! "$(which unzip)" ]; then
			egrep -v -i '\.zip$'
		else
			cat
		fi |\
		if [ "$OPT_NO_FTP" = true ]; then
			egrep -v '^ftp:'
		else
			cat
		fi
}

process_default_urls() {
	default_urls | shuf | {
			# Keep in mind that the pipe created a subshell
			while read URL; do
				process_url "$WORK_DIR" "$URL" && exit
			done
			exit 1
		} && return 0

	echo "Could not find any suitable URL" >&2
	return 1
}

main() {
	set_default_args
	parse_args "$@"
	[ "$OPT_FORCE" != true ] && verify_sanity

	# Make sure the directory exists before going any further
	misc_dir >/dev/null

	# Temporary workspace
	local WORK_DIR="$(mktemp --directory --tmpdir)"
	trap "rm -rf '$WORK_DIR'" EXIT

	if [ "$OPT_SOURCE" ]; then
		process_file_or_url "$WORK_DIR" "$OPT_SOURCE"
	else
		process_default_urls "$WORK_DIR"
	fi

	fakeroot dpkg-deb --build "$WORK_DIR/build" .

	rm -rf "$WORK_DIR"
	trap - EXIT
}

main "$@"
